---
sudo: false
language: python
matrix:
  include:
    - os: linux
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  dist: trusty
    #  language: generic
    #  sudo: true
    #  env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  language: generic
    #  sudo: true
    #  env: TOXENV=py35-32-pyqt5
    - os: osx
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  sudo: false
    #  python: 3.5
    #  env: TOXENV=docs
addons:
  apt:
    packages:
      - pandoc
      - build-essential
      - curl
      - git
      - python-setuptools
      - ruby
      - gist
before_install:
  - source ./.travis/helper.sh
  - source ./.travis/gist.sh
  - source ./.travis/update_packages.sh
  #- source ./.travis/qt.sh
  - export PATH='~/genial/pyqtdeploy/qt-5.7.0/bin':$PATH
  - source ./.travis/pandoc.sh
  - source ./.travis/pyenv.sh
  - source ./.travis/doit.sh
install:
  - doit
      download_static_qt
      extract_static_qt
      configure_static_qt
      make_static_qt
      make_install_static_qt
  - doit
      download_static_python
      extract_static_python
      configure_static_python
      qmake_static_python
      make_static_python
      make_install_static_python
  - doit
      download_static_sip
      extract_static_sip
      configure_static_sip
      qmake_static_sip
      make_static_sip
      make_install_static_sip
  - doit
      download_static_pyqt5
      extract_static_pyqt5
      configure_static_pyqt5
      make_static_pyqt5
      make_install_static_pyqt5
  - doit
script:
  - tox
