---
sudo: false
language: python
matrix:
  include:
    - os: linux
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    - os: linux
      language: generic
      sudo: false
      env: TOXENV=py35-32-pyqt5
    - os: osx
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
      cache:
        directories:
          - $HOME/sip-4.18
          - $HOME/PyQt5_gpl-5.6
    #- os: linux
    #  sudo: false
    #  python: 3.5
    #  env: TOXENV=docs
addons:
  apt:
    packages:
      - pandoc
      - build-essential
      - curl
      - git
      - python-setuptools
      - ruby
before_install:
  - ./.travis/before_install.sh
install:
  - ./.travis/install.sh
script:
  - "python setup.py bootstrap"
  - "python setup.py test"
