---
sudo: false
language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=py35-64-pyqt5
    - os: linux
      language: generic
      sudo: required
      env: TOXENV=py35-32-pyqt5
    - os: osx
      language: generic
      sudo: required
      env: TOXENV=py35-64-pyqt5
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=docs
addons:
  apt:
    packages:
      - pandoc
before_install:
  - ./.travis/before_install.sh
install:
  - ./.travis/install.sh
script:
  - "python setup.py bootstrap"
  - "python setup.py test"
