---
sudo: false
language: python
matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: true
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  language: generic
    #  sudo: true
    #  env: TOXENV=py35-32-pyqt5
    - os: osx
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  sudo: false
    #  python: 3.5
    #  env: TOXENV=docs
addons:
  apt:
    packages:
      - pandoc
      - build-essential
      - curl
      - git
      - python-setuptools
      - ruby
before_install:
  - source ./.travis/helper.sh
  - source ./.travis/update_packages.sh
  - source ./.travis/qt.sh
  - source ./.travis/pandoc.sh
  - source ./.travis/pyenv.sh
install:
  - pip install doit
  - doit
  - doit download_qt_source
  - doit extract_qt_source
  - doit configure_qt_source
  - doit make_qt_source
  - doit make_install_qt_source
script:
  - tox
