---
sudo: false
language: python
matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: true
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  language: generic
    #  sudo: true
    #  env: TOXENV=py35-32-pyqt5
    - os: osx
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  sudo: false
    #  python: 3.5
    #  env: TOXENV=docs
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pandoc
      - build-essential
      - curl
      - git
      - mercurial
      - python-setuptools
      - ruby
      - rubygems-integration
      - make
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - wget
      - curl
      - llvm
      - xz-utils
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install bash && alias bash=/usr/local/Cellar/bash/4.4/bin/bash; fi
  - source .travis/env.sh
  - pushd .travis && bash setup_packages.sh && popd
  - pushd .travis && bash gist.sh && popd
  - pushd .travis && bash pyenv.sh && popd
  - eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"
  - pushd .travis && bash qt.sh && popd
  - pushd .travis && bash doit.sh && popd
install:
  - doit
script:
  - tox
