---
sudo: false
language: python
matrix:
  include:
    - os: linux
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  dist: trusty
    #  language: generic
    #  sudo: true
    #  env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  language: generic
    #  sudo: true
    #  env: TOXENV=py35-32-pyqt5
    - os: osx
      language: generic
      sudo: false
      env: TOXENV=py35-64-pyqt5
    #- os: linux
    #  sudo: false
    #  python: 3.5
    #  env: TOXENV=docs
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pandoc
      - build-essential
      - curl
      - git
      - mercurial
      - python-setuptools
      - ruby
      - rubygems
      - make
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - wget
      - curl
      - llvm
      - xz-utils
      - gcc-5
      - g++-5
      - libxcb-composite0
      - libxcb-damage0
      - libxcb-dpms0
      - libxcb-dri2-0
      - libxcb-ewmh1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-record0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-res0
      - libxcb-screensaver0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync0
      - libxcb-util0
      - libxcb-xevie0
      - libxcb-xf86dri0
      - libxcb-xinerama0
      - libxcb-xprint0
      - libxcb-xtest0
      - libxcb-xv0
      - libxcb-xvmc0
      - libxmb1
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install bash && alias bash=/usr/local/Cellar/bash/4.4/bin/bash; fi
  - source .travis/env.sh
  - pushd .travis && bash setup_packages.sh && popd
  - pushd .travis && bash gist.sh && popd
  - pushd .travis && bash qt.sh && popd
  - pushd .travis && bash pyenv.sh && popd
  - eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"
  - pushd .travis && bash doit.sh && popd
install:
  - doit
script:
  - tox
